name: Deploy Packages

on: push # must be on merge

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Build Common
        run: npm run build:common
      - name: Publish Common
        run: npm run publish:common
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build Material
        run: npm run build:material
      - name: Publish Material
        run: npm run publish:material
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build Custom
        run: npm run build:custom
      - name: Publish Custom
        run: npm run publish:custom
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
